import { Country, Sector } from '../types';

export const AFRICAN_COUNTRIES: Country[] = [
  { id: 'ZA', code: 'ZA', name: 'Afrique du Sud', flag: '🇿🇦', region: 'Southern Africa', status: 'ACTIVE' },
  { id: 'DZ', code: 'DZ', name: 'Algérie', flag: '🇩🇿', region: 'North Africa', status: 'ACTIVE' },
  { id: 'AO', code: 'AO', name: 'Angola', flag: '🇦🇴', region: 'Central Africa', status: 'ACTIVE' },
  { id: 'BJ', code: 'BJ', name: 'Bénin', flag: '🇧🇯', region: 'West Africa', status: 'ACTIVE' },
  { id: 'BW', code: 'BW', name: 'Botswana', flag: '🇧🇼', region: 'Southern Africa', status: 'ACTIVE' },
  { id: 'BF', code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', region: 'West Africa', status: 'ACTIVE' },
  { id: 'BI', code: 'BI', name: 'Burundi', flag: '🇧🇮', region: 'East Africa', status: 'ACTIVE' },
  { id: 'CM', code: 'CM', name: 'Cameroun', flag: '🇨🇲', region: 'Central Africa', status: 'ACTIVE' },
  { id: 'CV', code: 'CV', name: 'Cap-Vert', flag: '🇨🇻', region: 'West Africa', status: 'ACTIVE' },
  { id: 'CF', code: 'CF', name: 'République centrafricaine', flag: '🇨🇫', region: 'Central Africa', status: 'ACTIVE' },
  { id: 'TD', code: 'TD', name: 'Tchad', flag: '🇹🇩', region: 'Central Africa', status: 'ACTIVE' },
  { id: 'KM', code: 'KM', name: 'Comores', flag: '🇰🇲', region: 'East Africa', status: 'ACTIVE' },
  { id: 'CG', code: 'CG', name: 'Congo', flag: '🇨🇬', region: 'Central Africa', status: 'ACTIVE' },
  { id: 'CD', code: 'CD', name: 'République démocratique du Congo', flag: '🇨🇩', region: 'Central Africa', status: 'ACTIVE' },
  { id: 'DJ', code: 'DJ', name: 'Djibouti', flag: '🇩🇯', region: 'East Africa', status: 'ACTIVE' },
  { id: 'EG', code: 'EG', name: 'Égypte', flag: '🇪🇬', region: 'North Africa', status: 'ACTIVE' },
  { id: 'GQ', code: 'GQ', name: 'Guinée équatoriale', flag: '🇬🇶', region: 'Central Africa', status: 'ACTIVE' },
  { id: 'ER', code: 'ER', name: 'Érythrée', flag: '🇪🇷', region: 'East Africa', status: 'ACTIVE' },
  { id: 'SZ', code: 'SZ', name: 'Eswatini', flag: '🇸🇿', region: 'Southern Africa', status: 'ACTIVE' },
  { id: 'ET', code: 'ET', name: 'Éthiopie', flag: '🇪🇹', region: 'East Africa', status: 'ACTIVE' },
  { id: 'GA', code: 'GA', name: 'Gabon', flag: '🇬🇦', region: 'Central Africa', status: 'ACTIVE' },
  { id: 'GM', code: 'GM', name: 'Gambie', flag: '🇬🇲', region: 'West Africa', status: 'ACTIVE' },
  { id: 'GH', code: 'GH', name: 'Ghana', flag: '🇬🇭', region: 'West Africa', status: 'ACTIVE' },
  { id: 'GN', code: 'GN', name: 'Guinée', flag: '🇬🇳', region: 'West Africa', status: 'ACTIVE' },
  { id: 'GW', code: 'GW', name: 'Guinée-Bissau', flag: '🇬🇼', region: 'West Africa', status: 'ACTIVE' },
  { id: 'CI', code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮', region: 'West Africa', status: 'ACTIVE' },
  { id: 'KE', code: 'KE', name: 'Kenya', flag: '🇰🇪', region: 'East Africa', status: 'ACTIVE' },
  { id: 'LS', code: 'LS', name: 'Lesotho', flag: '🇱🇸', region: 'Southern Africa', status: 'ACTIVE' },
  { id: 'LR', code: 'LR', name: 'Liberia', flag: '🇱🇷', region: 'West Africa', status: 'ACTIVE' },
  { id: 'LY', code: 'LY', name: 'Libye', flag: '🇱🇾', region: 'North Africa', status: 'ACTIVE' },
  { id: 'MG', code: 'MG', name: 'Madagascar', flag: '🇲🇬', region: 'East Africa', status: 'ACTIVE' },
  { id: 'MW', code: 'MW', name: 'Malawi', flag: '🇲🇼', region: 'East Africa', status: 'ACTIVE' },
  { id: 'ML', code: 'ML', name: 'Mali', flag: '🇲🇱', region: 'West Africa', status: 'ACTIVE' },
  { id: 'MR', code: 'MR', name: 'Mauritanie', flag: '🇲🇷', region: 'West Africa', status: 'ACTIVE' },
  { id: 'MU', code: 'MU', name: 'Maurice', flag: '🇲🇺', region: 'East Africa', status: 'ACTIVE' },
  { id: 'MA', code: 'MA', name: 'Maroc', flag: '🇲🇦', region: 'North Africa', status: 'ACTIVE' },
  { id: 'MZ', code: 'MZ', name: 'Mozambique', flag: '🇲🇿', region: 'Southern Africa', status: 'ACTIVE' },
  { id: 'NA', code: 'NA', name: 'Namibie', flag: '🇳🇦', region: 'Southern Africa', status: 'ACTIVE' },
  { id: 'NE', code: 'NE', name: 'Niger', flag: '🇳🇪', region: 'West Africa', status: 'ACTIVE' },
  { id: 'NG', code: 'NG', name: 'Nigeria', flag: '🇳🇬', region: 'West Africa', status: 'ACTIVE' },
  { id: 'RW', code: 'RW', name: 'Rwanda', flag: '🇷🇼', region: 'East Africa', status: 'ACTIVE' },
  { id: 'ST', code: 'ST', name: 'Sao Tomé-et-Principe', flag: '🇸🇹', region: 'Central Africa', status: 'ACTIVE' },
  { id: 'SN', code: 'SN', name: 'Sénégal', flag: '🇸🇳', region: 'West Africa', status: 'ACTIVE' },
  { id: 'SC', code: 'SC', name: 'Seychelles', flag: '🇸🇨', region: 'East Africa', status: 'ACTIVE' },
  { id: 'SL', code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', region: 'West Africa', status: 'ACTIVE' },
  { id: 'SO', code: 'SO', name: 'Somalie', flag: '🇸🇴', region: 'East Africa', status: 'ACTIVE' },
  { id: 'SS', code: 'SS', name: 'Soudan du Sud', flag: '🇸🇸', region: 'East Africa', status: 'ACTIVE' },
  { id: 'SD', code: 'SD', name: 'Soudan', flag: '🇸🇩', region: 'North Africa', status: 'ACTIVE' },
  { id: 'TZ', code: 'TZ', name: 'Tanzanie', flag: '🇹🇿', region: 'East Africa', status: 'ACTIVE' },
  { id: 'TG', code: 'TG', name: 'Togo', flag: '🇹🇬', region: 'West Africa', status: 'ACTIVE' },
  { id: 'TN', code: 'TN', name: 'Tunisie', flag: '🇹🇳', region: 'North Africa', status: 'ACTIVE' },
  { id: 'UG', code: 'UG', name: 'Ouganda', flag: '🇺🇬', region: 'East Africa', status: 'ACTIVE' },
  { id: 'ZM', code: 'ZM', name: 'Zambie', flag: '🇿🇲', region: 'Southern Africa', status: 'ACTIVE' },
  { id: 'ZW', code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', region: 'Southern Africa', status: 'ACTIVE' }
];

export const SECTORS: Sector[] = [
  { id: 'agriculture', name: 'Agriculture' },
  { id: 'agroalimentaire', name: 'Agroalimentaire' },
  { id: 'artisanat', name: 'Artisanat' },
  { id: 'commerce', name: 'Commerce' },
  { id: 'education', name: 'Éducation' },
  { id: 'finance', name: 'Finance' },
  { id: 'immobilier', name: 'Immobilier' },
  { id: 'industrie', name: 'Industrie' },
  { id: 'mode_textile', name: 'Mode & Textile' },
  { id: 'numerique_technologie', name: 'Numérique & Technologie' },
  { id: 'sante', name: 'Santé' },
  { id: 'tourisme', name: 'Tourisme' },
  { id: 'transport_logistique', name: 'Transport & Logistique' },
  { id: 'services', name: 'Services' },
  { id: 'communication_medias', name: 'Communication & Médias' },
  { id: 'energie', name: 'Énergie' },
  { id: 'environnement', name: 'Environnement' },
  { id: 'conseil', name: 'Conseil' },
  { id: 'beaute_bienetre', name: 'Beauté & Bien-être' },
  { id: 'culture_creation', name: 'Culture & Création' }
];
