import { Entrepreneur, Article, Project } from '../types';

export const DEMO_ARTICLES: Article[] = [
  {
    id: "1",
    title: "Le rôle des femmes dans la transition énergétique en Afrique",
    slug: "role-femmes-transition-energetique",
    excerpt: "Comment les entrepreneures africaines mènent la charge vers des solutions énergétiques durables.",
    content: "...",
    featuredImage: "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&q=80&w=600",
    categoryId: "energie",
    tags: ["Solaire", "Climat"],
    authorId: "author-1",
    authorName: "Fatoumata Bâ",
    status: "PUBLISHED",
    publishedAt: Date.now() - 86400000 * 2,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: "2",
    title: "Financement des PME : Les nouvelles opportunités pour 2024",
    slug: "financement-pme-opportunites-2024",
    excerpt: "Tour d'horizon des fonds d'investissement dédiés aux femmes entrepreneures sur le continent.",
    content: "...",
    featuredImage: "https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&q=80&w=600",
    categoryId: "finance",
    tags: ["Investissement", "Levée de fonds"],
    authorId: "author-2",
    authorName: "Équipe FAFE",
    status: "PUBLISHED",
    publishedAt: Date.now() - 86400000 * 5,
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 5,
  },
  {
    id: "3",
    title: "Agrobusiness : Transformer localement pour exporter globalement",
    slug: "agrobusiness-transformer-localement-exporter",
    excerpt: "Les stratégies gagnantes pour conquérir les marchés internationaux avec des produits locaux.",
    content: "...",
    featuredImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&q=80&w=600",
    categoryId: "agrobusiness",
    tags: ["Agriculture", "Commerce International"],
    authorId: "author-3",
    authorName: "Amina Diallo",
    status: "PUBLISHED",
    publishedAt: Date.now() - 86400000 * 10,
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 10,
  }
];

export const DEMO_PROJECTS: Project[] = [
  {
    id: "1",
    title: "Programme d'Incubation Tech & Femmes",
    description: "Accompagnement de 50 femmes dans le développement de startups technologiques à fort impact.",
    image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=600",
    country: "Panafricain",
    status: "ACTIVE",
    targetAmount: 500000,
    raisedAmount: 380000,
    donationEnabled: true,
    updatedAt: Date.now(),
    objectives: ["Former 50 fondatrices", "Lancer 10 MVP", "Faciliter 5 levées de fonds"],
    impact: "Création de 120 emplois directs dans le secteur technologique.",
    createdAt: Date.now(),
  },
  {
    id: "2",
    title: "Accès au financement rural",
    description: "Fonds de micro-crédit rotatif pour les coopératives agricoles féminines.",
    image: "https://images.unsplash.com/photo-1593113565694-c68174549929?auto=format&fit=crop&q=80&w=600",
    country: "Sénégal, Mali, Burkina Faso",
    status: "ACTIVE",
    targetAmount: 150000,
    raisedAmount: 45000,
    donationEnabled: true,
    updatedAt: Date.now(),
    objectives: ["Soutenir 200 coopératives", "Fournir des équipements de transformation"],
    impact: "Augmentation de 40% des revenus moyens des bénéficiaires.",
    createdAt: Date.now(),
  },
];

export const DEMO_ENTREPRENEURS: Entrepreneur[] = [
  {
    id: "1",
    firstName: "Amina",
    lastName: "Diallo",
    professionalPhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop",
    country: "Sénégal",
    city: "Dakar",
    sector: "Agrobusiness",
    company: "Sunu Terroir",
    position: "Fondatrice & CEO",
    description: "Passionnée par la valorisation des produits locaux africains. Sunu Terroir transforme et exporte des céréales locales (fonio, mil) avec un impact social fort sur les coopératives de femmes en zone rurale.",
    expertise: ["Agroalimentaire", "Exportation", "Management d'équipe"],
    productsServices: ["Fonio précuit", "Farine de mil enrichie"],
    website: "https://example.com",
    status: "APPROVED",
    verificationStatus: "VERIFIED",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDemo: true
  },
  {
    id: "2",
    firstName: "Fatou",
    lastName: "Ndiaye",
    professionalPhoto: "https://images.unsplash.com/photo-1589156229687-496a31ad1d1f?q=80&w=600&auto=format&fit=crop",
    country: "Côte d'Ivoire",
    city: "Abidjan",
    sector: "Tech & Numérique",
    company: "AfriTech Solutions",
    position: "Directrice Générale",
    description: "Développement de solutions logicielles adaptées aux réalités des PME africaines. Nous aidons les entreprises à digitaliser leurs processus de gestion financière.",
    expertise: ["Génie Logiciel", "Fintech", "Stratégie Digitale"],
    productsServices: ["ERP PME", "Application de paiement"],
    status: "APPROVED",
    verificationStatus: "VERIFIED",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDemo: true
  },
  {
    id: "3",
    firstName: "Nneka",
    lastName: "Okafor",
    professionalPhoto: "https://images.unsplash.com/photo-1531123414708-5369786a5f54?q=80&w=600&auto=format&fit=crop",
    country: "Nigeria",
    city: "Lagos",
    sector: "Mode & Design",
    company: "Okafor Studios",
    position: "Directrice Créative",
    description: "Création de vêtements éco-responsables mêlant artisanat traditionnel nigérian et coupes modernes. Notre marque est distribuée dans 5 pays africains.",
    expertise: ["Design de Mode", "Textile Durable", "E-commerce"],
    productsServices: ["Collection prêt-à-porter", "Accessoires en cuir vegan"],
    status: "APPROVED",
    verificationStatus: "VERIFIED",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDemo: true
  },
  {
    id: "4",
    firstName: "Mariam",
    lastName: "Keita",
    professionalPhoto: "https://images.unsplash.com/photo-1523824922771-22815617387e?q=80&w=600&auto=format&fit=crop",
    country: "Mali",
    city: "Bamako",
    sector: "Énergies Renouvelables",
    company: "Bamako Solar",
    position: "Co-fondatrice",
    description: "Installation de mini-réseaux solaires pour les villages non électrifiés. Nous visons à fournir une énergie propre et abordable aux populations rurales.",
    expertise: ["Ingénierie Solaire", "Gestion de Projet", "Impact Social"],
    productsServices: ["Kits solaires domestiques", "Mini-réseaux"],
    status: "APPROVED",
    verificationStatus: "VERIFIED",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDemo: true
  }
];

export const DEMO_EVENTS = [
  {
    id: "evt-1",
    title: "Forum Panafricain des Femmes Entrepreneures 2024",
    slug: "forum-panafricain-2024",
    shortDescription: "Le plus grand rassemblement annuel de l'entrepreneuriat féminin en Afrique.",
    description: "Rejoignez plus de 1000 femmes d'affaires pour deux jours de conférences, ateliers et networking intensif.",
    coverImage: "https://images.unsplash.com/photo-1540317580384-e5d43867caa6?auto=format&fit=crop&q=80&w=800",
    startDate: Date.now() + 86400000 * 30, // in 30 days
    endDate: Date.now() + 86400000 * 32,
    location: { type: 'PHYSICAL', address: 'Dakar, Sénégal', coordinates: { lat: 0, lng: 0 } },
    city: "Dakar",
    country: "Sénégal",
    online: false,
    status: "REGISTRATION_OPEN",
    registrationEnabled: true,
    capacity: 1000,
    price: 150000,
    currency: "XOF",
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: "evt-2",
    title: "Masterclass: Lever des fonds pour sa startup",
    slug: "masterclass-levee-fonds",
    shortDescription: "Apprenez les clés pour réussir votre levée de fonds auprès d'investisseurs internationaux.",
    description: "Une session intensive de 4 heures avec des experts du capital-risque africain.",
    coverImage: "https://images.unsplash.com/photo-1556761175-5973dc0f32d7?auto=format&fit=crop&q=80&w=800",
    startDate: Date.now() + 86400000 * 15,
    endDate: Date.now() + 86400000 * 15,
    location: { type: 'VIRTUAL', link: 'https://zoom.us/...' },
    city: "En ligne",
    country: "International",
    online: true,
    status: "REGISTRATION_OPEN",
    registrationEnabled: true,
    capacity: 100,
    price: 0,
    currency: "XOF",
    createdAt: Date.now(),
    updatedAt: Date.now()
  },
  {
    id: "evt-3",
    title: "Networking & Business Angels Meetup",
    slug: "networking-business-angels-abidjan",
    shortDescription: "Rencontrez des investisseurs locaux et régionaux pour propulser votre entreprise.",
    description: "Soirée de networking exclusif avec le club des Business Angels d'Abidjan.",
    coverImage: "https://images.unsplash.com/photo-1515169067868-5387ec356754?auto=format&fit=crop&q=80&w=800",
    startDate: Date.now() + 86400000 * 45,
    endDate: Date.now() + 86400000 * 45,
    location: { type: 'PHYSICAL', address: 'Hôtel Ivoire, Abidjan' },
    city: "Abidjan",
    country: "Côte d'Ivoire",
    online: false,
    status: "PUBLISHED",
    registrationEnabled: true,
    capacity: 200,
    price: 50000,
    currency: "XOF",
    createdAt: Date.now(),
    updatedAt: Date.now()
  }
];
