import { Entrepreneur, Article, Project } from '../types';

export const DEMO_ARTICLES: Article[] = [
  {
    id: "1",
    title: "Le rôle des femmes dans la transition énergétique en Afrique",
    excerpt: "Comment les entrepreneures africaines mènent la charge vers des solutions énergétiques durables.",
    content: "...",
    featuredImage: "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&q=80&w=600",
    author: "Fatoumata Bâ",
    categories: ["Énergie", "Innovation"],
    tags: ["Solaire", "Climat"],
    publicationDate: Date.now() - 86400000 * 2,
  },
  {
    id: "2",
    title: "Financement des PME : Les nouvelles opportunités pour 2024",
    excerpt: "Tour d'horizon des fonds d'investissement dédiés aux femmes entrepreneures sur le continent.",
    content: "...",
    featuredImage: "https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&q=80&w=600",
    author: "Équipe FAFE",
    categories: ["Finance", "Croissance"],
    tags: ["Investissement", "Levée de fonds"],
    publicationDate: Date.now() - 86400000 * 5,
  },
  {
    id: "3",
    title: "Agrobusiness : Transformer localement pour exporter globalement",
    excerpt: "Les stratégies gagnantes pour conquérir les marchés internationaux avec des produits locaux.",
    content: "...",
    featuredImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&q=80&w=600",
    author: "Amina Diallo",
    categories: ["Agrobusiness", "Export"],
    tags: ["Agriculture", "Commerce International"],
    publicationDate: Date.now() - 86400000 * 10,
  }
];

export const DEMO_PROJECTS: Project[] = [
  {
    id: "1",
    title: "Programme d'Incubation Tech & Femmes",
    description: "Accompagnement de 50 femmes dans le développement de startups technologiques à fort impact.",
    image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=600",
    country: "Panafricain",
    status: "ACTIVE",
    objectives: ["Former 50 fondatrices", "Lancer 10 MVP", "Faciliter 5 levées de fonds"],
    impact: "Création de 120 emplois directs dans le secteur technologique.",
    createdAt: Date.now(),
  },
  {
    id: "2",
    title: "Accès au financement rural",
    description: "Fonds de micro-crédit rotatif pour les coopératives agricoles féminines.",
    image: "https://images.unsplash.com/photo-1593113565694-c68174549929?auto=format&fit=crop&q=80&w=600",
    country: "Sénégal, Mali, Burkina Faso",
    status: "ACTIVE",
    objectives: ["Soutenir 200 coopératives", "Fournir des équipements de transformation"],
    impact: "Augmentation de 40% des revenus moyens des bénéficiaires.",
    createdAt: Date.now(),
  },
];

export const DEMO_ENTREPRENEURS: Entrepreneur[] = [
  {
    id: "1",
    firstName: "Amina",
    lastName: "Diallo",
    professionalPhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop",
    country: "Sénégal",
    city: "Dakar",
    sector: "Agrobusiness",
    company: "Sunu Terroir",
    position: "Fondatrice & CEO",
    description: "Passionnée par la valorisation des produits locaux africains. Sunu Terroir transforme et exporte des céréales locales (fonio, mil) avec un impact social fort sur les coopératives de femmes en zone rurale.",
    expertise: ["Agroalimentaire", "Exportation", "Management d'équipe"],
    productsServices: ["Fonio précuit", "Farine de mil enrichie"],
    website: "https://example.com",
    status: "ACTIVE",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDemo: true
  },
  {
    id: "2",
    firstName: "Fatou",
    lastName: "Ndiaye",
    professionalPhoto: "https://images.unsplash.com/photo-1589156229687-496a31ad1d1f?q=80&w=600&auto=format&fit=crop",
    country: "Côte d'Ivoire",
    city: "Abidjan",
    sector: "Tech & Numérique",
    company: "AfriTech Solutions",
    position: "Directrice Générale",
    description: "Développement de solutions logicielles adaptées aux réalités des PME africaines. Nous aidons les entreprises à digitaliser leurs processus de gestion financière.",
    expertise: ["Génie Logiciel", "Fintech", "Stratégie Digitale"],
    productsServices: ["ERP PME", "Application de paiement"],
    status: "ACTIVE",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDemo: true
  },
  {
    id: "3",
    firstName: "Nneka",
    lastName: "Okafor",
    professionalPhoto: "https://images.unsplash.com/photo-1531123414708-5369786a5f54?q=80&w=600&auto=format&fit=crop",
    country: "Nigeria",
    city: "Lagos",
    sector: "Mode & Design",
    company: "Okafor Studios",
    position: "Directrice Créative",
    description: "Création de vêtements éco-responsables mêlant artisanat traditionnel nigérian et coupes modernes. Notre marque est distribuée dans 5 pays africains.",
    expertise: ["Design de Mode", "Textile Durable", "E-commerce"],
    productsServices: ["Collection prêt-à-porter", "Accessoires en cuir vegan"],
    status: "ACTIVE",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDemo: true
  },
  {
    id: "4",
    firstName: "Mariam",
    lastName: "Keita",
    professionalPhoto: "https://images.unsplash.com/photo-1523824922771-22815617387e?q=80&w=600&auto=format&fit=crop",
    country: "Mali",
    city: "Bamako",
    sector: "Énergies Renouvelables",
    company: "Bamako Solar",
    position: "Co-fondatrice",
    description: "Installation de mini-réseaux solaires pour les villages non électrifiés. Nous visons à fournir une énergie propre et abordable aux populations rurales.",
    expertise: ["Ingénierie Solaire", "Gestion de Projet", "Impact Social"],
    productsServices: ["Kits solaires domestiques", "Mini-réseaux"],
    status: "ACTIVE",
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isDemo: true
  }
];
